version: '3.8'
services:
  postgres-movie-be:
    container_name: postgres-movie-be
    image: postgres
    environment:
      POSTGRES_USER: dbmoviebe
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: moviebe
      PGDATA: /data/postgres
    volumes:
      - postgres-movie-be:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres-movie-be: